site_name: PythonGuide
repo_url: https://github.com/Sakura4036/PythonGuide
repo_name: Sakura4036/PythonGuide
site_url: https://github.com/Sakura4036/PythonGuide

nav:
    - 主页: index.md
    - 项目开发:
        - 基础:
            - 项目结构: guidelines/project_structure.md
            - 日志: guidelines/logging.md
            - 配置文件: guidelines/configuration.md
            - 文档管理: guidelines/document.md
        - 进阶:
            - 代码检测: guidelines/code_lint.md
            - 设计模式: guidelines/program_design.md
            - 代码重构: guidelines/code_refactor.md
    - Python规范:
        - 语言规范: standard/language_rules.md
        - 风格规范: standard/style_rules.md
    - Git版本控制: git.md
    - 设计模式: 
        设计模式: patterns/patterns.md
        Gang of Four: 
            - 基础原则: patterns/gang of four/principles.md
            - 创建型模式: patterns/gang of four/creational patterns.md
            - 结构型模式: patterns/gang of four/structural patterns.md
            - 行为型模式: patterns/gang of four/behavioral patterns.md
            
    - 参考目录: reference.md


#主题
theme:
  name: 'material'
  language: 'zh'  # 配置语言
  palette:  # 颜色
    primary: 'light blue'
    #accent: 'indigo'
  features:
    - navigation.tabs
    - search.highlight
    - navigation.tracking   # 锚点导航, url显示，可以用于超链接定位
  custom_dir: 'docs/resources/'

markdown_extensions:
  - admonition  # 提示块
  - footnotes  # 脚注
  - meta  # 定义元数据，通过文章上下文控制，如disqus
  - pymdownx.caret  # 下划线上标
  - pymdownx.tilde  # 删除线下标
  - pymdownx.critic  # 增加删除修改高亮注释，可修饰行内或段落
  - pymdownx.details  # 提示块可折叠
  - pymdownx.inlinehilite  # 行内代码高亮
  - pymdownx.mark  # 文本高亮
  - pymdownx.smartsymbols  # 符号转换
  - pymdownx.superfences  # 代码嵌套在列表里
  - codehilite:    # 代码高亮，显示行号
      guess_lang: false
      linenums: true
  - toc:  # 锚点
      permalink: true
#  - pymdownx.arithmatex  # 数学公式
  - pymdownx.betterem:  # 对加粗和斜体更好的检测
      smart_enable: all
#  - pymdownx.emoji:  # 表情
#      emoji_generator: !!python/name:pymdownx.emoji.to_svg
#  - pymdownx.magiclink  # 自动识别超链接
  - pymdownx.tasklist:  # 复选框checklist
      custom_checkbox: true

plugins:
    - search